{
    'name': 'Solvera OJT Core',
    'summary': 'Inti modul manajemen On-the-Job Training (OJT) — batch, peserta, tugas, absensi, sertifikat.',
    'version': '1.0.0',
    'category': 'Human Resources/Training',
    'author': 'Najib',
    'license': 'LGPL-3',
    'website': 'https://solvera.id',
    'depends': [
        'hr_recruitment',
        'event',
        'website_slides',
        'survey',
        'portal',
        'website',
        'mail',
    ],
    'data': [
        'data/ir_sequence.xml',
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/ojt_batch_views.xml',
    ],
    'application': True,
    'installable': True,
}
